### ISSUE TITLE
Unfortunately, AppLauncher has stopped

### ISSUE THREAD

**Issue by DaikoShiota** [HappyZ/dpt-tools#94]
Hi, HappyZ

I enjoy your good works for DPT. 

Now I have encountered a problem after doing 
Method 3 in the Upgrade Guide. 
My DPT says "Unfortunately, AppLauncher has stopped" 
and continues to display "Please wait..." even if I press the cancel botton.

I have tried Method 2 and Method 3 for several times  but those did 
not solve the above problem.

Do you have any idea to escape from my problem?

**Comment by Enzo-Liu** [comment]
#92 
using this method here `https://github.com/HappyZ/dpt-tools/issues/92#issuecomment-493723767`, I've fixed the same problem. 
You can try that too.

**Comment by DaikoShiota** [comment]
Dear Enzo-Liu,

Thank you very much.
I did not notice it. I will try it.

**Comment by HappyZ** [comment]
@Enzo-Liu thx, added that to wiki

**Comment by DaikoShiota** [comment]
Dear Enzo-Liu and HappyZ, 
Thank you again for your help. 
Although I have tried the method in https://github.com/HappyZ/dpt-tools/wiki/Suggested-Launcher-Mod,
any launcher cannot open and the dialog "Please wait..." with cancel button  seems not to finish. 

I have also tried the methods in https://github.com/HappyZ/dpt-tools/wiki/PKGs-I-Made 
for several times. But my problem is not solved.

**Comment by HappyZ** [comment]
Please read the wiki. In upgrade guide, after updates. You press cancel and
it will eventually gone. Press HOME and create a folder named Note. Or you
can choose to reset instead.

**Comment by HappyZ** [comment]
closed as no further questions

to sum up, you just need to be a bit patient and wait for a little longer until you can actually cancel
